name: flutter_clean_arch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  auto_injector: ^2.0.5
  realm: ^3.4.1
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  result_dart: ^1.1.1
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
